version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8401:8401"
    volumes:
      - ./backend:/app/backend
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./app:/app/app
    restart: always
